CHAPTERS = [
    {
        "chapter_id": 1,
        "title_cz": "Pozdravy",
        "title_sk": "Pozdravy",
        "title_th": "การทักทาย",
        "level": "začátečník",
        "words": [
            {"th": "สวัสดี", "cz": "dobrý den", "sk": "dobrý deň"},
            {"th": "ครับ", "cz": "ano / částice (muži)", "sk": "áno / častica (muži)"},
            {"th": "ค่ะ", "cz": "ano / částice (ženy)", "sk": "áno / častica (ženy)"},
            {"th": "ขอบคุณ", "cz": "děkuji", "sk": "ďakujem"},
            {"th": "ขอโทษ", "cz": "promiňte", "sk": "prepáčte"},
            {"th": "ไม่เป็นไร", "cz": "to nic, není zač", "sk": "to nič, niet za čo"},
            {"th": "ลาก่อน", "cz": "na shledanou", "sk": "dovidenia"},
            {"th": "สบายดีไหม", "cz": "jak se máte?", "sk": "ako sa máte?"},
            {"th": "สบายดี", "cz": "mám se dobře", "sk": "mám sa dobre"},
            {"th": "ยินดีที่ได้รู้จัก", "cz": "těší mě", "sk": "teší ma"},
            {"th": "ใช่", "cz": "ano", "sk": "áno"},
            {"th": "ไม่ใช่", "cz": "ne", "sk": "nie"},
            {"th": "พบกันใหม่", "cz": "na viděnou", "sk": "do videnia"},
            {"th": "โชคดี", "cz": "hodně štěstí", "sk": "veľa šťastia"},
            {"th": "ฉัน", "cz": "já (ženy)", "sk": "ja (ženy)"},
            {"th": "ผม", "cz": "já (muži)", "sk": "ja (muži)"},
            {"th": "คุณ", "cz": "vy / ty", "sk": "vy / ty"},
            {"th": "เขา", "cz": "on / ona", "sk": "on / ona"},
            {"th": "เรา", "cz": "my", "sk": "my"},
            {"th": "พบ", "cz": "potkat", "sk": "stretnúť"}
        ],
        "sentences": [
            {"th": "สวัสดีครับ", "cz": "Dobrý den (říká muž).", "sk": "Dobrý deň (hovorí muž)."},
            {"th": "สวัสดีค่ะ", "cz": "Dobrý den (říká žena).", "sk": "Dobrý deň (hovorí žena)."},
            {"th": "ขอบคุณครับ", "cz": "Děkuji (říká muž).", "sk": "Ďakujem (hovorí muž)."},
            {"th": "สบายดีไหมครับ", "cz": "Jak se máte?", "sk": "Ako sa máte?"},
            {"th": "ฉันสบายดีค่ะ", "cz": "Mám se dobře (říká žena).", "sk": "Mám sa dobre (hovorí žena)."},
            {"th": "ผมสบายดีครับ", "cz": "Mám se dobře (říká muž).", "sk": "Mám sa dobre (hovorí muž)."},
            {"th": "ยินดีที่ได้รู้จักครับ", "cz": "Těší mě.", "sk": "Teší ma."},
            {"th": "ขอโทษค่ะ", "cz": "Promiňte (říká žena).", "sk": "Prepáčte (hovorí žena)."},
            {"th": "ไม่เป็นไรครับ", "cz": "To nic (říká muž).", "sk": "To nič (hovorí muž)."},
            {"th": "พบกันใหม่ค่ะ", "cz": "Na viděnou.", "sk": "Do videnia."}
        ]
    },
    {
        "chapter_id": 2,
        "title_cz": "Čísla 0–20",
        "title_sk": "Čísla 0–20",
        "title_th": "ตัวเลข 0–20",
        "level": "začátečník",
        "words": [
            {"th": "ศูนย์", "cz": "nula", "sk": "nula"},
            {"th": "หนึ่ง", "cz": "jedna", "sk": "jeden"},
            {"th": "สอง", "cz": "dva", "sk": "dva"},
            {"th": "สาม", "cz": "tři", "sk": "tri"},
            {"th": "สี่", "cz": "čtyři", "sk": "štyri"},
            {"th": "ห้า", "cz": "pět", "sk": "päť"},
            {"th": "หก", "cz": "šest", "sk": "šesť"},
            {"th": "เจ็ด", "cz": "sedm", "sk": "sedem"},
            {"th": "แปด", "cz": "osm", "sk": "osem"},
            {"th": "เก้า", "cz": "devět", "sk": "deväť"},
            {"th": "สิบ", "cz": "deset", "sk": "desať"},
            {"th": "เอ็ด", "cz": "jeden (v číslovkách)", "sk": "jeden (v číslovkách)"},
            {"th": "สิบเอ็ด", "cz": "jedenáct", "sk": "jedenásť"},
            {"th": "สิบสอง", "cz": "dvanáct", "sk": "dvanásť"},
            {"th": "สิบสาม", "cz": "třináct", "sk": "trinásť"},
            {"th": "สิบสี่", "cz": "čtrnáct", "sk": "štrnásť"},
            {"th": "ยี่สิบ", "cz": "dvacet", "sk": "dvadsať"},
            {"th": "เท่าไหร่", "cz": "kolik", "sk": "koľko"},
            {"th": "อายุ", "cz": "věk", "sk": "vek"},
            {"th": "ปี", "cz": "rok", "sk": "rok"}
        ],
        "sentences": [
            {"th": "หนึ่ง สอง สาม", "cz": "Jedna, dva, tři.", "sk": "Jeden, dva, tri."},
            {"th": "อายุเท่าไหร่ครับ", "cz": "Kolik je vám let?", "sk": "Koľko máte rokov?"},
            {"th": "ผมอายุยี่สิบปี", "cz": "Je mi dvacet let.", "sk": "Mám dvadsať rokov."},
            {"th": "มีห้า", "cz": "Je jich pět.", "sk": "Je ich päť."},
            {"th": "มีสิบสอง", "cz": "Je jich dvanáct.", "sk": "Je ich dvanásť."},
            {"th": "เขาอายุสิบแปดปี", "cz": "Je mu osmnáct let.", "sk": "Má osemnásť rokov."},
            {"th": "มีเท่าไหร่", "cz": "Kolik toho je?", "sk": "Koľko toho je?"},
            {"th": "ผมมีสาม", "cz": "Mám tři.", "sk": "Mám tri."},
            {"th": "คุณมีสิบ", "cz": "Máte deset.", "sk": "Máte desať."},
            {"th": "เขาอายุเก้าปี", "cz": "Je mu devět let.", "sk": "Má deväť rokov."}
        ]
    },
    {
        "chapter_id": 3,
        "title_cz": "Barvy",
        "title_sk": "Farby",
        "title_th": "สี",
        "level": "začátečník",
        "words": [
            {"th": "สี", "cz": "barva", "sk": "farba"},
            {"th": "สีแดง", "cz": "červená", "sk": "červená"},
            {"th": "สีน้ำเงิน", "cz": "modrá", "sk": "modrá"},
            {"th": "สีเขียว", "cz": "zelená", "sk": "zelená"},
            {"th": "สีเหลือง", "cz": "žlutá", "sk": "žltá"},
            {"th": "สีดำ", "cz": "černá", "sk": "čierna"},
            {"th": "สีขาว", "cz": "bílá", "sk": "biela"},
            {"th": "สีส้ม", "cz": "oranžová", "sk": "oranžová"},
            {"th": "สีชมพู", "cz": "růžová", "sk": "ružová"},
            {"th": "สีม่วง", "cz": "fialová", "sk": "fialová"},
            {"th": "สีน้ำตาล", "cz": "hnědá", "sk": "hnedá"},
            {"th": "สีเทา", "cz": "šedá", "sk": "sivá"},
            {"th": "สีฟ้า", "cz": "světle modrá", "sk": "svetlomodrá"},
            {"th": "ชอบ", "cz": "líbit se", "sk": "páčiť sa"},
            {"th": "อะไร", "cz": "co / jaký", "sk": "čo / aký"},
            {"th": "อ่อน", "cz": "světlý", "sk": "svetlý"},
            {"th": "เข้ม", "cz": "tmavý", "sk": "tmavý"},
            {"th": "สวย", "cz": "krásný", "sk": "krásny"},
            {"th": "มาก", "cz": "velmi", "sk": "veľmi"},
            {"th": "เสื้อ", "cz": "košile / tričko", "sk": "košeľa / tričko"}
        ],
        "sentences": [
            {"th": "คุณชอบสีอะไรครับ", "cz": "Jakou barvu máte rádi?", "sk": "Akú farbu máte radi?"},
            {"th": "ฉันชอบสีแดงค่ะ", "cz": "Mám ráda červenou.", "sk": "Mám rada červenú."},
            {"th": "เขาชอบสีน้ำเงิน", "cz": "On má rád modrou.", "sk": "On má rád modrú."},
            {"th": "เสื้อสีขาว", "cz": "Bílá košile.", "sk": "Biela košeľa."},
            {"th": "สีดำสวยมาก", "cz": "Černá je velmi krásná.", "sk": "Čierna je veľmi krásna."},
            {"th": "ผมชอบสีเขียว", "cz": "Mám rád zelenou.", "sk": "Mám rád zelenú."},
            {"th": "เสื้อสีเหลือง", "cz": "Žluté tričko.", "sk": "Žlté tričko."},
            {"th": "สีชมพูสวยค่ะ", "cz": "Růžová je hezká.", "sk": "Ružová je pekná."},
            {"th": "สีส้มอ่อน", "cz": "Světle oranžová.", "sk": "Svetlo oranžová."},
            {"th": "สีเทาเข้ม", "cz": "Tmavě šedá.", "sk": "Tmavosivá."}
        ]
    },
    {
        "chapter_id": 4,
        "title_cz": "Rodina",
        "title_sk": "Rodina",
        "title_th": "ครอบครัว",
        "level": "začátečník",
        "words": [
            {"th": "ครอบครัว", "cz": "rodina", "sk": "rodina"},
            {"th": "พ่อ", "cz": "otec", "sk": "otec"},
            {"th": "แม่", "cz": "matka", "sk": "matka"},
            {"th": "ลูก", "cz": "dítě", "sk": "dieťa"},
            {"th": "ลูกชาย", "cz": "syn", "sk": "syn"},
            {"th": "ลูกสาว", "cz": "dcera", "sk": "dcéra"},
            {"th": "พี่ชาย", "cz": "starší bratr", "sk": "starší brat"},
            {"th": "น้องชาย", "cz": "mladší bratr", "sk": "mladší brat"},
            {"th": "พี่สาว", "cz": "starší sestra", "sk": "staršia sestra"},
            {"th": "น้องสาว", "cz": "mladší sestra", "sk": "mladšia sestra"},
            {"th": "ปู่", "cz": "dědeček (z otcovy strany)", "sk": "dedko (z otcovej strany)"},
            {"th": "ย่า", "cz": "babička (z otcovy strany)", "sk": "babka (z otcovej strany)"},
            {"th": "ตา", "cz": "dědeček (z matčiny strany)", "sk": "dedko (z matkinej strany)"},
            {"th": "ยาย", "cz": "babička (z matčiny strany)", "sk": "babka (z matkinej strany)"},
            {"th": "สามี", "cz": "manžel", "sk": "manžel"},
            {"th": "ภรรยา", "cz": "manželka", "sk": "manželka"},
            {"th": "แฟน", "cz": "přítel / přítelkyně", "sk": "priateľ / priateľka"},
            {"th": "เพื่อน", "cz": "kamarád", "sk": "kamarát"},
            {"th": "มี", "cz": "mít", "sk": "mať"},
            {"th": "รัก", "cz": "milovat", "sk": "milovať"}
        ],
        "sentences": [
            {"th": "ฉันรักครอบครัว", "cz": "Miluji svou rodinu.", "sk": "Milujem svoju rodinu."},
            {"th": "ผมมีพี่ชาย", "cz": "Mám staršího bratra.", "sk": "Mám staršieho brata."},
            {"th": "เขามีน้องสาว", "cz": "On má mladší sestru.", "sk": "On má mladšiu sestru."},
            {"th": "พ่อรักแม่", "cz": "Otec miluje matku.", "sk": "Otec miluje matku."},
            {"th": "ตากับยาย", "cz": "Dědeček a babička.", "sk": "Dedko a babka."},
            {"th": "ฉันมีลูกชายสองคน", "cz": "Mám dva syny.", "sk": "Mám dvoch synov."},
            {"th": "แฟนของผม", "cz": "Moje přítelkyně.", "sk": "Moja priateľka."},
            {"th": "ครอบครัวของฉัน", "cz": "Moje rodina.", "sk": "Moja rodina."},
            {"th": "เราเป็นเพื่อนกัน", "cz": "Jsme přátelé.", "sk": "Sme priatelia."},
            {"th": "คุณมีพี่น้องไหม", "cz": "Máte sourozence?", "sk": "Máte súrodencov?"}
        ]
    },
    {
        "chapter_id": 5,
        "title_cz": "Jídlo a pití",
        "title_sk": "Jedlo a pitie",
        "title_th": "อาหารและเครื่องดื่ม",
        "level": "mírně pokročilý",
        "words": [
            {"th": "อาหาร", "cz": "jídlo", "sk": "jedlo"},
            {"th": "น้ำ", "cz": "voda", "sk": "voda"},
            {"th": "ข้าว", "cz": "rýže", "sk": "ryža"},
            {"th": "กิน", "cz": "jíst", "sk": "jesť"},
            {"th": "ดื่ม", "cz": "pít", "sk": "piť"},
            {"th": "อร่อย", "cz": "chutný", "sk": "chutný"},
            {"th": "เผ็ด", "cz": "pálivý", "sk": "pikantný"},
            {"th": "หวาน", "cz": "sladký", "sk": "sladký"},
            {"th": "เค็ม", "cz": "slaný", "sk": "slaný"},
            {"th": "เปรี้ยว", "cz": "kyselý", "sk": "kyslý"},
            {"th": "หมู", "cz": "vepřové", "sk": "bravčové"},
            {"th": "ไก่", "cz": "kuřecí", "sk": "kuracie"},
            {"th": "ปลา", "cz": "ryba", "sk": "ryba"},
            {"th": "ผัก", "cz": "zelenina", "sk": "zelenina"},
            {"th": "ผลไม้", "cz": "ovoce", "sk": "ovocie"},
            {"th": "กาแฟ", "cz": "káva", "sk": "káva"},
            {"th": "ชา", "cz": "čaj", "sk": "čaj"},
            {"th": "หิว", "cz": "mít hlad", "sk": "byť hladný"},
            {"th": "อิ่ม", "cz": "být sytý", "sk": "byť sýty"},
            {"th": "ร้านอาหาร", "cz": "restaurace", "sk": "reštaurácia"}
        ],
        "sentences": [
            {"th": "ฉันหิวข้าว", "cz": "Mám hlad.", "sk": "Som hladný."},
            {"th": "อาหารอร่อยมาก", "cz": "Jídlo je velmi chutné.", "sk": "Jedlo je veľmi chutné."},
            {"th": "ผมไม่กินเผ็ด", "cz": "Nejím pálivé.", "sk": "Nejem pikantné."},
            {"th": "ขอน้ำครับ", "cz": "Prosím vodu.", "sk": "Prosím vodu."},
            {"th": "ฉันชอบผลไม้", "cz": "Mám ráda ovoce.", "sk": "Mám rada ovocie."},
            {"th": "กาแฟร้อน", "cz": "Horká káva.", "sk": "Horúca káva."},
            {"th": "กินข้าวกับไก่", "cz": "Jíst rýži s kuřecím.", "sk": "Jesť ryžu s kuracím."},
            {"th": "ปลาอร่อยไหม", "cz": "Je ryba dobrá?", "sk": "Je ryba dobrá?"},
            {"th": "ผมอิ่มแล้ว", "cz": "Jsem plný.", "sk": "Som plný."},
            {"th": "ไปร้านอาหาร", "cz": "Jít do restaurace.", "sk": "Ísť do reštaurácie."}
        ]
    },
    {
        "chapter_id": 6,
        "title_cz": "Čas a dny",
        "title_sk": "Čas a dni",
        "title_th": "เวลาและวัน",
        "level": "mírně pokročilý",
        "words": [
            {"th": "เวลา", "cz": "čas", "sk": "čas"},
            {"th": "วัน", "cz": "den", "sk": "deň"},
            {"th": "เดือน", "cz": "měsíc", "sk": "mesiac"},
            {"th": "วันนี้", "cz": "dnes", "sk": "dnes"},
            {"th": "พรุ่งนี้", "cz": "zítra", "sk": "zajtra"},
            {"th": "เมื่อวาน", "cz": "včera", "sk": "včera"},
            {"th": "เช้า", "cz": "ráno", "sk": "ráno"},
            {"th": "บ่าย", "cz": "odpoledne", "sk": "poobedie"},
            {"th": "เย็น", "cz": "večer", "sk": "večer"},
            {"th": "คืน", "cz": "noc", "sk": "noc"},
            {"th": "วันจันทร์", "cz": "pondělí", "sk": "pondelok"},
            {"th": "วันอังคาร", "cz": "úterý", "sk": "utorok"},
            {"th": "วันพุธ", "cz": "středa", "sk": "streda"},
            {"th": "วันพฤหัสบดี", "cz": "čtvrtek", "sk": "štvrtok"},
            {"th": "วันศุกร์", "cz": "pátek", "sk": "piatok"},
            {"th": "วันเสาร์", "cz": "sobota", "sk": "sobota"},
            {"th": "วันอาทิตย์", "cz": "neděle", "sk": "nedeľa"},
            {"th": "ชั่วโมง", "cz": "hodina", "sk": "hodina"},
            {"th": "นาที", "cz": "minuta", "sk": "minúta"},
            {"th": "ตอนนี้", "cz": "teď", "sk": "teraz"}
        ],
        "sentences": [
            {"th": "วันนี้วันจันทร์", "cz": "Dnes je pondělí.", "sk": "Dnes je pondelok."},
            {"th": "พรุ่งนี้วันอังคาร", "cz": "Zítra je úterý.", "sk": "Zajtra je utorok."},
            {"th": "ตอนเช้า", "cz": "Ráno.", "sk": "Ráno."},
            {"th": "เจอกันตอนบ่าย", "cz": "Uvidíme se odpoledne.", "sk": "Uvidíme sa poobede."},
            {"th": "เมื่อวานสนุกมาก", "cz": "Včera to byla zábava.", "sk": "Včera to bola zábava."},
            {"th": "ตอนนี้เวลาเท่าไหร่", "cz": "Kolik je teď hodin?", "sk": "Koľko je teraz hodín?"},
            {"th": "สามชั่วโมง", "cz": "Tři hodiny.", "sk": "Tri hodiny."},
            {"th": "เจอกันวันศุกร์", "cz": "Uvidíme se v pátek.", "sk": "Uvidíme sa v piatok."},
            {"th": "ตอนเย็นกินข้าว", "cz": "Večer jím jídlo.", "sk": "Večer jem jedlo."},
            {"th": "เดือนนี้", "cz": "Tento měsíc.", "sk": "Tento mesiac."}
        ]
    },
    {
        "chapter_id": 7,
        "title_cz": "Doprava",
        "title_sk": "Doprava",
        "title_th": "การคมนาคม",
        "level": "mírně pokročilý",
        "words": [
            {"th": "รถ", "cz": "auto", "sk": "auto"},
            {"th": "รถเมล์", "cz": "autobus", "sk": "autobus"},
            {"th": "รถไฟ", "cz": "vlak", "sk": "vlak"},
            {"th": "แท็กซี่", "cz": "taxi", "sk": "taxi"},
            {"th": "เครื่องบิน", "cz": "letadlo", "sk": "lietadlo"},
            {"th": "ไป", "cz": "jít / jet", "sk": "ísť"},
            {"th": "มา", "cz": "přijít", "sk": "prísť"},
            {"th": "ซ้าย", "cz": "vlevo", "sk": "vľavo"},
            {"th": "ขวา", "cz": "vpravo", "sk": "vpravo"},
            {"th": "ตรงไป", "cz": "rovně", "sk": "rovno"},
            {"th": "ใกล้", "cz": "blízko", "sk": "blízko"},
            {"th": "ไกล", "cz": "daleko", "sk": "ďaleko"},
            {"th": "ที่ไหน", "cz": "kde", "sk": "kde"},
            {"th": "ถนน", "cz": "ulice", "sk": "ulica"},
            {"th": "สถานี", "cz": "stanice", "sk": "stanica"},
            {"th": "สนามบิน", "cz": "letiště", "sk": "letisko"},
            {"th": "ขับรถ", "cz": "řídit", "sk": "šoférovať"},
            {"th": "เดิน", "cz": "chodit pěšky", "sk": "kráčať"},
            {"th": "จอด", "cz": "zastavit", "sk": "zastaviť"},
            {"th": "ทาง", "cz": "cesta", "sk": "cesta"}
        ],
        "sentences": [
            {"th": "รถไฟไปที่ไหน", "cz": "Kam jede vlak?", "sk": "Kam ide vlak?"},
            {"th": "สนามบินอยู่ไกลไหม", "cz": "Je letiště daleko?", "sk": "Je letisko ďaleko?"},
            {"th": "สถานีอยู่ใกล้", "cz": "Stanice je blízko.", "sk": "Stanica je blízko."},
            {"th": "เลี้ยวซ้าย", "cz": "Zahněte doleva.", "sk": "Odbočte doľava."},
            {"th": "เลี้ยวขวา", "cz": "Zahněte doprava.", "sk": "Odbočte doprava."},
            {"th": "เดินตรงไป", "cz": "Jděte rovně.", "sk": "Choďte rovno."},
            {"th": "ผมขับรถ", "cz": "Řídím auto.", "sk": "Šoférujem auto."},
            {"th": "แท็กซี่มาแล้ว", "cz": "Taxík už přijel.", "sk": "Taxík už prišiel."},
            {"th": "จอดที่นี่ครับ", "cz": "Zastavte tady, prosím.", "sk": "Zastavte tu, prosím."},
            {"th": "ไปรถเมล์", "cz": "Jet autobusem.", "sk": "Ísť autobusom."}
        ]
    },
    {
        "chapter_id": 8,
        "title_cz": "Tělo",
        "title_sk": "Telo",
        "title_th": "ร่างกาย",
        "level": "mírně pokročilý",
        "words": [
            {"th": "ร่างกาย", "cz": "tělo", "sk": "telo"},
            {"th": "หัว", "cz": "hlava", "sk": "hlava"},
            {"th": "ตา", "cz": "oko", "sk": "oko"},
            {"th": "หู", "cz": "ucho", "sk": "ucho"},
            {"th": "จมูก", "cz": "nos", "sk": "nos"},
            {"th": "ปาก", "cz": "ústa", "sk": "ústa"},
            {"th": "ฟัน", "cz": "zub", "sk": "zub"},
            {"th": "ผม", "cz": "vlasy", "sk": "vlasy"},
            {"th": "มือ", "cz": "ruka", "sk": "ruka"},
            {"th": "แขน", "cz": "paže", "sk": "paže"},
            {"th": "ขา", "cz": "noha", "sk": "noha"},
            {"th": "เท้า", "cz": "chodidlo", "sk": "chodidlo"},
            {"th": "เจ็บ", "cz": "bolet", "sk": "bolieť"},
            {"th": "ป่วย", "cz": "být nemocný", "sk": "byť chorý"},
            {"th": "ยา", "cz": "lék", "sk": "liek"},
            {"th": "หมอ", "cz": "doktor", "sk": "doktor"},
            {"th": "โรงพยาบาล", "cz": "nemocnice", "sk": "nemocnica"},
            {"th": "เหนื่อย", "cz": "unavený", "sk": "unavený"},
            {"th": "พักผ่อน", "cz": "odpočívat", "sk": "odpočívať"},
            {"th": "ดีขึ้น", "cz": "zlepšit se", "sk": "zlepšiť sa"}
        ],
        "sentences": [
            {"th": "ผมเจ็บหัว", "cz": "Bolí mě hlava.", "sk": "Bolí ma hlava."},
            {"th": "ฉันป่วย", "cz": "Jsem nemocná.", "sk": "Som chorá."},
            {"th": "ไปหาหมอ", "cz": "Jít k doktorovi.", "sk": "Ísť k doktorovi."},
            {"th": "โรงพยาบาลอยู่ไหน", "cz": "Kde je nemocnice?", "sk": "Kde je nemocnica?"},
            {"th": "กินยา", "cz": "Vzít si lék.", "sk": "Vziať si liek."},
            {"th": "ตาของเขา", "cz": "Jeho oči.", "sk": "Jeho oči."},
            {"th": "เจ็บฟัน", "cz": "Bolí mě zub.", "sk": "Bolí ma zub."},
            {"th": "ผมเหนื่อยมาก", "cz": "Jsem velmi unavený.", "sk": "Som veľmi unavený."},
            {"th": "พักผ่อนหน่อย", "cz": "Trochu si odpočiň.", "sk": "Trochu si odpočiň."},
            {"th": "ดีขึ้นไหม", "cz": "Je to lepší?", "sk": "Je to lepšie?"}
        ]
    },
    {
        "chapter_id": 9,
        "title_cz": "Nakupování",
        "title_sk": "Nakupovanie",
        "title_th": "การช้อปปิ้ง",
        "level": "mírně pokročilý",
        "words": [
            {"th": "ซื้อ", "cz": "koupit", "sk": "kúpiť"},
            {"th": "ขาย", "cz": "prodat", "sk": "predať"},
            {"th": "เงิน", "cz": "peníze", "sk": "peniaze"},
            {"th": "บาท", "cz": "baht", "sk": "baht"},
            {"th": "แพง", "cz": "drahý", "sk": "drahý"},
            {"th": "ถูก", "cz": "levný", "sk": "lacný"},
            {"th": "ราคา", "cz": "cena", "sk": "cena"},
            {"th": "เท่าไหร่", "cz": "kolik", "sk": "koľko"},
            {"th": "ลดราคา", "cz": "sleva", "sk": "zľava"},
            {"th": "ร้านค้า", "cz": "obchod", "sk": "obchod"},
            {"th": "ตลาด", "cz": "trh", "sk": "trh"},
            {"th": "กระเป๋า", "cz": "taška", "sk": "taška"},
            {"th": "รองเท้า", "cz": "boty", "sk": "topánky"},
            {"th": "เสื้อผ้า", "cz": "oblečení", "sk": "oblečenie"},
            {"th": "กางเกง", "cz": "kalhoty", "sk": "nohavice"},
            {"th": "จ่าย", "cz": "platit", "sk": "platiť"},
            {"th": "ใบ", "cz": "klasifikátor (věci)", "sk": "klasifikátor (veci)"},
            {"th": "ตัว", "cz": "klasifikátor (oblečení, zvířata)", "sk": "klasifikátor (oblečenie, zvieratá)"},
            {"th": "อยากได้", "cz": "chtít (věc)", "sk": "chcieť (vec)"},
            {"th": "สวย", "cz": "krásný", "sk": "krásny"}
        ],
        "sentences": [
            {"th": "ราคาเท่าไหร่ครับ", "cz": "Kolik to stojí?", "sk": "Koľko to stojí?"},
            {"th": "แพงมาก", "cz": "Velmi drahé.", "sk": "Veľmi drahé."},
            {"th": "ลดราคาได้ไหม", "cz": "Můžete dát slevu?", "sk": "Môžete dať zľavu?"},
            {"th": "อันนี้ถูก", "cz": "Tohle je levné.", "sk": "Toto je lacné."},
            {"th": "ฉันอยากได้กระเป๋า", "cz": "Chci tašku.", "sk": "Chcem tašku."},
            {"th": "ซื้อเสื้อผ้าที่ตลาด", "cz": "Kupovat oblečení na trhu.", "sk": "Kupovať oblečenie na trhu."},
            {"th": "รองเท้าสวย", "cz": "Krásné boty.", "sk": "Krásne topánky."},
            {"th": "จ่ายเงินที่ไหน", "cz": "Kde mohu zaplatit?", "sk": "Kde môžem zaplatiť?"},
            {"th": "มีเงินร้อยบาท", "cz": "Mám sto bahtů.", "sk": "Mám sto bahtov."},
            {"th": "ขายดีไหม", "cz": "Prodává se to dobře?", "sk": "Predáva sa to dobre?"}
        ]
    },
    {
        "chapter_id": 10,
        "title_cz": "Příroda a počasí",
        "title_sk": "Príroda a počasie",
        "title_th": "ธรรมชาติและสภาพอากาศ",
        "level": "pokročilý začátečník",
        "words": [
            {"th": "ธรรมชาติ", "cz": "příroda", "sk": "príroda"},
            {"th": "อากาศ", "cz": "počasí / vzduch", "sk": "počasie / vzduch"},
            {"th": "ร้อน", "cz": "horko", "sk": "horúco"},
            {"th": "หนาว", "cz": "zima", "sk": "zima"},
            {"th": "เย็น", "cz": "chladno", "sk": "chladno"},
            {"th": "ฝน", "cz": "déšť", "sk": "dážď"},
            {"th": "แดด", "cz": "slunce (svit)", "sk": "slnko (svit)"},
            {"th": "ลม", "cz": "vítr", "sk": "vietor"},
            {"th": "ตก", "cz": "padat (pršet)", "sk": "padať (pršať)"},
            {"th": "ทะเล", "cz": "moře", "sk": "more"},
            {"th": "ภูเขา", "cz": "hora", "sk": "hora"},
            {"th": "ต้นไม้", "cz": "strom", "sk": "strom"},
            {"th": "ดอกไม้", "cz": "květina", "sk": "kvetina"},
            {"th": "ท้องฟ้า", "cz": "obloha", "sk": "obloha"},
            {"th": "ดวงอาทิตย์", "cz": "slunce", "sk": "slnko"},
            {"th": "ดวงจันทร์", "cz": "měsíc", "sk": "mesiac"},
            {"th": "ดาว", "cz": "hvězda", "sk": "hviezda"},
            {"th": "สวย", "cz": "krásný", "sk": "krásny"},
            {"th": "ฤดู", "cz": "roční období", "sk": "ročné obdobie"},
            {"th": "เที่ยว", "cz": "cestovat / výlet", "sk": "cestovať / výlet"}
        ],
        "sentences": [
            {"th": "วันนี้อากาศร้อน", "cz": "Dnes je horko.", "sk": "Dnes je horúco."},
            {"th": "ฝนตกไหม", "cz": "Prší?", "sk": "Prší?"},
            {"th": "พรุ่งนี้หนาว", "cz": "Zítra bude zima.", "sk": "Zajtra bude zima."},
            {"th": "ลมแรงมาก", "cz": "Vítr je velmi silný.", "sk": "Vietor je veľmi silný."},
            {"th": "ไปเที่ยวทะเล", "cz": "Jet na výlet k moři.", "sk": "Ísť na výlet k moru."},
            {"th": "ภูเขาสวยมาก", "cz": "Hora je velmi krásná.", "sk": "Hora je veľmi krásna."},
            {"th": "แดดร้อน", "cz": "Slunce pálí.", "sk": "Slnko páli."},
            {"th": "ดอกไม้สีแดง", "cz": "Červená květina.", "sk": "Červená kvetina."},
            {"th": "ท้องฟ้าสวย", "cz": "Krásná obloha.", "sk": "Krásna obloha."},
            {"th": "ดาวเยอะมาก", "cz": "Mnoho hvězd.", "sk": "Veľa hviezd."}
        ]
    }
]
